In [1]:
import nltk

In [3]:
nltk.download()

showing info https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/index.xml


True

In [4]:
#corpus - A Large Collection of Text

In [2]:
from nltk.corpus import brown
print(brown.categories())

['adventure', 'belles_lettres', 'editorial', 'fiction', 'government', 'hobbies', 'humor', 'learned', 'lore', 'mystery', 'news', 'religion', 'reviews', 'romance', 'science_fiction']


In [3]:
print(len(brown.categories()))

15


In [9]:
data = brown.sents(categories='adventure')

In [12]:
print(len(data))

4637


In [14]:
' '.join(data[1])

'He was well rid of her .'

In [15]:
#Tokenization
sentance = "Send all the 50 documents to satyams2812@gmail.com"
from nltk.tokenize import sent_tokenize, word_tokenize


In [16]:
from nltk.tokenize import RegexpTokenizer


In [19]:
tokenizer = RegexpTokenizer('[a-zA-Z@.]+')
useful_text = tokenizer.tokenize(sentance)

In [20]:
useful_text

['Send', 'all', 'the', 'documents', 'to', 'satyams', '@gmail.com']

In [21]:
#Ste,,omg
#process that  transoftm particular words(verbs, plurals) into their radical form
#Presever the semanticss of the sentance without increasing the number of unique token
#Examples  - jumps, jumping, jump , jump ==> jump

In [22]:
text = """Foxes love to make jumps. The quick brown fox was seen jumping over the lovely dog from a 6ft feet high wall"""

In [25]:
from nltk.stem.snowball import SnowballStemmer, PorterStemmer
 

In [27]:
 ps = PorterStemmer()
 ps.stem('jumping')

'jump'

In [29]:
#Building a Vocab & Vectorization
#Each document  = feature documents
corpus = ['indian cricket team will wins world cup, says cap. Virat', "We will win next Lok sabha elections, says confident Indian PM", 'The nobel laurate won the hearts of the people' , 'The movie raazi is an exciting indian spy thriller based upon a real story']

In [32]:
#Find unique words then create the vector
from sklearn.feature_extraction.text import CountVectorizer

In [33]:
cv = CountVectorizer()

In [50]:
vectorized_corpus = cv.fit_transform(corpus)

In [51]:
vectorized_corpus = vectorized_corpus.toarray()

In [52]:
print(len(vectorized_corpus[0]))

36


In [53]:
cv.vocabulary_

{'indian': 9,
 'cricket': 4,
 'team': 25,
 'will': 31,
 'wins': 33,
 'world': 35,
 'cup': 5,
 'says': 22,
 'cap': 2,
 'virat': 29,
 'we': 30,
 'win': 32,
 'next': 14,
 'lok': 12,
 'sabha': 21,
 'elections': 6,
 'confident': 3,
 'pm': 18,
 'the': 26,
 'nobel': 15,
 'laurate': 11,
 'won': 34,
 'hearts': 8,
 'of': 16,
 'people': 17,
 'movie': 13,
 'raazi': 19,
 'is': 10,
 'an': 0,
 'exciting': 7,
 'spy': 23,
 'thriller': 27,
 'based': 1,
 'upon': 28,
 'real': 20,
 'story': 24}

In [54]:
print(cv.vocabulary_)

{'indian': 9, 'cricket': 4, 'team': 25, 'will': 31, 'wins': 33, 'world': 35, 'cup': 5, 'says': 22, 'cap': 2, 'virat': 29, 'we': 30, 'win': 32, 'next': 14, 'lok': 12, 'sabha': 21, 'elections': 6, 'confident': 3, 'pm': 18, 'the': 26, 'nobel': 15, 'laurate': 11, 'won': 34, 'hearts': 8, 'of': 16, 'people': 17, 'movie': 13, 'raazi': 19, 'is': 10, 'an': 0, 'exciting': 7, 'spy': 23, 'thriller': 27, 'based': 1, 'upon': 28, 'real': 20, 'story': 24}


In [56]:
 #Reverse mapping
 numbers = vectorized_corpus[2]
 s = c v.inverse_transform(numbers)

ValueError: Expected 2D array, got 1D array instead:
array=[0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 1 1 1 0 0 0 0 0 0 0 0 3 0 0 0 0 0 0 0 1 0].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [59]:
#vectorization with stopwords
def myTokenizer(document): 
    words = tokenizer.tokenize(document .lower())
    #remove stopwors
    words = remove_stopwords(words,sw)
    return words

In [ ]:
cv = CountVectorizer(tokenizer=myTokenizer)

In [60]:
myTokenizer("this is some function")

NameError: name 'remove_stopwords' is not defined

In [61]:
#more way to create features
#unigram - every words as a feature
#bigram  - every pair as a feature
#Trigram
#N- gram 
#TF - IDF Normalization

In [65]:
sent_1 = ["this is good movie"]
sent_2 = ["this is good movie but actor is not present"]
sent_3 = ["this is not good movie"]

In [66]:
cv = CountVectorizer()

In [69]:
docs  = [sent_1[0], sent_2[0], sent_3[0]]
cv.fit_transform(docs).toarray()

array([[0, 0, 1, 1, 1, 0, 0, 1],
       [1, 1, 1, 2, 1, 1, 1, 1],
       [0, 0, 1, 1, 1, 1, 0, 1]], dtype=int64)

In [70]:
 #bi - gram 
cv = CountVectorizer(ngram_range=(2,2))
docs  = [sent_1[0], sent_2[0], sent_3[0]]
cv.fit_transform(docs).toarray()


array([[0, 0, 1, 1, 0, 0, 0, 0, 1],
       [1, 1, 1, 1, 1, 1, 0, 1, 1],
       [0, 0, 1, 0, 1, 0, 1, 0, 1]], dtype=int64)

In [71]:
cv.vocabulary_

{'this is': 8,
 'is good': 3,
 'good movie': 2,
 'movie but': 5,
 'but actor': 1,
 'actor is': 0,
 'is not': 4,
 'not present': 7,
 'not good': 6}

In [72]:
 #trigram 
cv = CountVectorizer(ngram_range=(3,3))
 #ngram
cv = CountVectorizer(ngram_range=(1,3))



In [73]:
#Tf-idf Normalization
#avoid features that occur very often, because they contain less information
#information decreases as the number of occurences increases acccross deffrent type of document
#so we define another term - term - document - frequence which associates a weight with every

In [74]:
sent_1 = "this is good movie"
sent_2 = "this was good movie"
sent_3 = "this is not good movie"
corpus = [sent_1,sent_2,sent_3]

In [75]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [79]:
tfidf = TfidfVectorizer()
vc = tfidf.fit_transform(corpus).toarray()

In [80]:
print(vc)

[[0.46333427 0.59662724 0.46333427 0.         0.46333427 0.        ]
 [0.41285857 0.         0.41285857 0.         0.41285857 0.69903033]
 [0.3645444  0.46941728 0.3645444  0.61722732 0.3645444  0.        ]]


In [81]:
tfidf.vocabulary_

{'this': 4, 'is': 1, 'good': 0, 'movie': 2, 'was': 5, 'not': 3}

In [15]:
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score

In [28]:
train_data = pd.read_csv("Train.csv", usecols=['review', 'label'])
test_data = pd.read_csv("Test.csv", usecols=['review'])


In [29]:
train_data['review'] = train_data['review'].str.lower()


In [30]:
vectorizer = CountVectorizer()
train_features = vectorizer.fit_transform(train_data['review'])

In [31]:
model = MultinomialNB()
model.fit(train_features, train_data['label'])

MultinomialNB()

In [32]:
test_features = vectorizer.transform(test_data['review'])

# Predict the sentiment of the test data
predictions = model.predict(test_features)


In [33]:
accuracy = accuracy_score(test_data['review'], predictions)
print("Accuracy: ", accuracy)


Accuracy:  0.0


In [34]:
def predict_sentiment(review):
    # Convert the review into numerical representation
    review_features = vectorizer.transform([review])
    
    # Predict the sentiment of the review
    prediction = model.predict(review_features)
    
    # Return the result
    if prediction[0] == 1:
        return "Positive"
    else:
        return "Negative"

In [35]:
predict_sentiment("This is good movie")

'Negative'

In [45]:
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score
import pickle

# Load the train data
train_data = pd.read_csv("Train.csv", usecols=['review', 'label'])


# Initialize the CountVectorizer and fit it to the train data
train_reviews = train_data['review'].tolist()
vectorizer = CountVectorizer()
review_features = vectorizer.fit_transform(train_data['review'])

# Train a Multinomial Naive Bayes model on the review features
model = MultinomialNB()
model.fit(review_features, train_data['label'])

# Load the test data

test_data = pd.read_csv("Test.csv", usecols=['review'])
test_reviews = test_data['review'].tolist()
# Convert the review into numerical representation
test_features = vectorizer.transform(test_data['review'])

# Predict the sentiment of the reviews
predictions = model.predict(test_features)


with open("movie_reviews_model.pkl", "wb") as file:
    pickle.dump(model, file)
    
# If you don't have the label column in the test data, you can't evaluate the accuracy of the model
# However, you can still use the predictions to classify the reviews as positive or negative
for prediction in predictions:
    if prediction == 1:
        print("Positive")
    else:
        print("Negative")


Negative
Negative
Negative
Negative
Negative
Negative
Negative
Negative
Negative
Negative
Negative
Negative
Negative
Negative
Negative
Negative
Negative
Negative
Negative
Negative
Negative
Negative
Negative
Negative
Negative
Negative
Negative
Negative
Negative
Negative
Negative
Negative
Negative
Negative
Negative
Negative
Negative
Negative
Negative
Negative
Negative
Negative
Negative
Negative
Negative
Negative
Negative
Negative
Negative
Negative
Negative
Negative
Negative
Negative
Negative
Negative
Negative
Negative
Negative
Negative
Negative
Negative
Negative
Negative
Negative
Negative
Negative
Negative
Negative
Negative
Negative
Negative
Negative
Negative
Negative
Negative
Negative
Negative
Negative
Negative
Negative
Negative
Negative
Negative
Negative
Negative
Negative
Negative
Negative
Negative
Negative
Negative
Negative
Negative
Negative
Negative
Negative
Negative
Negative
Negative
Negative
Negative
Negative
Negative
Negative
Negative
Negative
Negative
Negative
Negative
Negative
N

In [48]:
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB
import pickle

# Load the train data
train_data = pd.read_csv("Train.csv", usecols=['review', 'label'])

# Initialize the CountVectorizer and fit it to the train data
train_reviews = train_data['review'].tolist()
vectorizer = CountVectorizer()
review_features = vectorizer.fit_transform(train_data['review'])

# Train a Multinomial Naive Bayes model on the review features
model = MultinomialNB()
model.fit(review_features, train_data['label'])

# Save the model to a pickle file
with open("moviemodel.pkl", "wb") as file:
    pickle.dump(model, file)

In [1]:
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB
import pickle

# Load the train data
train_data = pd.read_csv("Train.csv", usecols=['review', 'label'])

# Initialize the CountVectorizer and fit it to the train data
train_reviews = train_data['review'].tolist()
vectorizer = CountVectorizer()
review_features = vectorizer.fit_transform(train_data['review'])

# Train a Multinomial Naive Bayes model on the review features
model = MultinomialNB()
model.fit(review_features, train_data['label'])

# Save the model to a pickle file
with open("movie_reviews_model.pkl", "wb") as file:
    pickle.dump(model, file)
with open("movie_reviews_vectorizer.pkl", "wb") as file:
    pickle.dump(vectorizer, file)

# Load the pickle file
with open("movie_reviews_model.pkl", "rb") as file:
    model = pickle.load(file)

# Initialize the vectorizer for the prediction
vectorizer = CountVectorizer(vocabulary=vectorizer.vocabulary_)

# Make a prediction on a new review
def predict_sentiment(review):
    review_features = vectorizer.transform([review])
    sentiment = model.predict(review_features)[0]
    return sentiment
